function gui_control_values = helper_getGUIControlValues(handles)
% get checkboxes and their values
gui_control_values = struct( ...
       'activation', logical(get(handles.cbox_activation, 'Value')), ...
       'trepanation', logical(get(handles.cbox_trepanation, 'Value')), ...
       'background_overlay', logical(get(handles.cbox_overlay, 'Value')), ...
       'background_only', logical(get(handles.tb_bg_only,'Value')), ...
       'showROI', logical(get(handles.cbox_showROI,'Value')), ...
       'electrode', logical(get(handles.cbox_electrode,'Value')), ... 
       'mask_contour', logical(get(handles.cbox_mask_contour,'Value')), ...
       'slider_threshold', handles.slider_threshold, ...
       'edit_threshold_cur', handles.edit_threshold_cur, ...
       'txt_notification', handles.txt_notification, ...
       'txt_cbar_bottom', handles.txt_cbar_bottom, ...
       'displayOutput', handles.displayOutput, ...
       'c_bar', handles.axes_cbar, ...
       'figure', findobj('Name','OI_analysis_DCS'), ...
       'popup_show', handles.popup_show, ...
       'show_legend', logical(get(handles.cbox_legend, 'Value'))); 
   
end %function